name = "moca-gating-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
# For local dev, database_id is not required (uses local SQLite)
[[d1_databases]]
binding = "DB"
database_name = "moca-invite-system-db"
database_id = "1af658b5-16c4-4893-babb-76ba414f7a36"

# KV namespace for rate limiting and caching
[[kv_namespaces]]
binding = "KV"
id = "d9a195c6b8db4b9f95c793c5bcf412af"

# Environment variables (will be set via wrangler secret put)
[vars]
SEPOLIA_RPC_URL = "https://eth-sepolia.g.alchemy.com/v2/YOUR_KEY"
STAKING_NFT_CONTRACT_ADDRESS = "0x88a1Dbe9568dDb8764EA10b279801E146Be6C531"

# Development overrides
[env.dev]
name = "moca-gating-backend-dev"

