name = "moca-gating-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
# For local dev, database_id is not required (uses local SQLite)
[[d1_databases]]
binding = "DB"
database_name = "moca-invite-system-db"
database_id = "placeholder" # Not needed for local dev, will be filled for production

# KV namespace for rate limiting and caching
# For local dev, preview_id will be used automatically
[[kv_namespaces]]
binding = "KV"
id = "placeholder" # Not needed for local dev
preview_id = "placeholder" # Local dev will use in-memory KV

# Environment variables (will be set via wrangler secret put)
[vars]
SEPOLIA_RPC_URL = "https://eth-sepolia.g.alchemy.com/v2/YOUR_KEY"
STAKING_NFT_CONTRACT_ADDRESS = "0x88a1Dbe9568dDb8764EA10b279801E146Be6C531"

# Development overrides
[env.dev]
name = "moca-gating-backend-dev"

